version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: cicddemo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      cicd-network:
        aliases:
          - database

  backend:
    container_name: cicddemo_backend
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root   # empty string since MYSQL_ALLOW_EMPTY_PASSWORD is true
      DB_NAME: appdb
    networks:
      - cicd-network

  frontend:
    container_name: cicddemo_frontend
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cicd-network

networks:
  cicd-network:
    driver: bridge